### ISSUE TITLE
Fix exporter error for MixedPoisson with P>=3

### ISSUE THREAD

**Issue by lsala** [feelpp/feelpp#1027]
There is a runtime error of memory in mixedpoisson when the polynomial order is greater or equal to 3 after the solver. The code seems to be the same as mixedelasticity that hasn't this kind of error.

**Comment by prudhomm** [comment]
Could you provide more details:
 - machine
 -, crash or wrong result? If wrong result please attach screen shot 
 -  command line to reproduce

**Comment by lsala** [comment]
To reproduce it: `./feelpp_toolbox_mixed-poisson-model_3DP3 --config-file mixed-poisson/test3d.cfg`


The error is a crash after it solves the problem:
` . Condensation done                                                                                                                                                     
 . starting Solve                                                                                                                                                        
 . Solve done                                                                                                                                                            
 . starting local Solve                                                                                                                                                  
[staticcondensation::localSolve]  N0=60 N1=20                                                                                                                            
 . local Solve done                                                                                                                                                      
   [MixedPoisson : static condensation] Time : 4.40076s                                                                                                                  
  [solve] Time : 4.40102s                                                                                                                                                
[mixedpoisson.MixedPoisson(0)] : [exportResults] : start                                                                                                                 
Integral value of potential(mup) on out :        5                                                                                                                       
Integral value of potential(from pp) on out :    5                                                                                                                       
*** Error in `./feelpp_toolbox_mixed-poisson-model_3DP3': free(): invalid pointer: 0x000000002461b080 ***                                                                
======= Backtrace: =========                                                                                                                                             
/lib/x86_64-linux-gnu/libc.so.6(+0x7908b)[0x7f6c3648408b]                                                                                                                
/lib/x86_64-linux-gnu/libc.so.6(+0x82c3a)[0x7f6c3648dc3a]                                                                                                                
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f6c36491d2c]                                                                                                              
./feelpp_toolbox_mixed-poisson-model_3DP3[0x926b87]                                                                                                                      
./feelpp_toolbox_mixed-poisson-model_3DP3(_ZNK4Feel2vf10IntegratorIN5boost6tuples5tupleIN4mpl_6size_tILm0EEEN9__gnu_cxx17__normal_iteratorIPKNS2_17reference_wrapperIKNS_
12GeoElement3DILt3ENS_7SimplexILt3ELt1ELt3EEEdEEEESt6vectorISG_SaISG_EEEESM_St10shared_ptrISL_ENS3_9null_typeESP_SP_SP_SP_SP_EENS_2_QILi3ENS_5GaussEEENS0_4ExprINS0_7Prod
uctINSU_INS0_6vf_subINSU_INSU_INS0_6vf_mulINS0_3CstIdEENSU_INS0_5TransINSU_INSU_INS0_11GinacMatrixILi1ELi3ELi2EEEEEEEEEEEEEEEEENSU_INS0_4OpIdINS_13FunctionSpaceINS_4Mesh
ISD_dLi0EEENS_5basesIJNS_8LagrangeILt3ENS_9VectorialENS_13DiscontinuousENS_18PointSetEquiSpacedELt0EEEEEEdNS_11PeriodicityIJNS_13NoPeriodicityEEEENS_7mortarsIJNS_8NoMort
arEEEEE7ElementIdNS_11VectorUblasIdNS2_7numeric5ublas6vectorIdNS1V_15unbounded_arrayIdSaIdEEEEEEEEELNS0_12OperatorTypeE2EEEEEEEEES27_Li1ELi1EEEEEST_E8evaluateENS5_4int_I
Li0EEE+0xaf9)[0x9774c9]                                                                                                                                                  
./feelpp_toolbox_mixed-poisson-model_3DP3(_ZN4Feel28boost_param_default_58normL2IdN5boost9parameter3aux8arg_listIKNS3_15tagged_argumentINS_3tag4exprEKNS_2vf4ExprINS8_6vf
_subINS9_INS9_INS8_6vf_mulINS8_3CstIdEENS9_INS8_5TransINS9_INS9_INS8_11GinacMatrixILi1ELi3ELi2EEEEEEEEEEEEEEEEENS9_INS8_4OpIdINS_13FunctionSpaceINS_4MeshINS_7SimplexILt3
ELt1ELt3EEEdLi0EEENS_5basesIJNS_8LagrangeILt3ENS_9VectorialENS_13DiscontinuousENS_18PointSetEquiSpacedELt0EEEEEEdNS_11PeriodicityIJNS_13NoPeriodicityEEEENS_7mortarsIJNS_
8NoMortarEEEEE7ElementIdNS_11VectorUblasIdNS1_7numeric5ublas6vectorIdNS1B_15unbounded_arrayIdSaIdEEEEEEEEELNS8_12OperatorTypeE2EEEEEEEEEEENS4_IKNS5_INS6_5rangeEKNS1_6tup
les5tupleIN4mpl_6size_tILm0EEEN9__gnu_cxx17__normal_iteratorIPKNS1_17reference_wrapperIKNS_12GeoElement3DILt3ESS_dEEEESt6vectorIS23_SaIS23_EEEES29_St10shared_ptrIS28_ENS
1S_9null_typeES2C_S2C_S2C_S2C_S2C_EEEENS3_14empty_arg_listEEEEES2E_S1O_bKNS_2_QILi3ENS_5GaussEEEKNS_18GeomapStrategyTypeES2N_bbiA5_KcbEET_PFS2S_vERKT0_iRT1_RT2_RT3_RT4_R
T5_RT6_RT7_RT8_RT9_RT10_RT11_+0x154)[0x974d94]  
./feelpp_toolbox_mixed-poisson-model_3DP3(_ZN4Feel10FeelModels12MixedPoissonILi3ELi3ELi1ELi4EE13exportResultsEdN5boost10shared_ptrINS_4MeshINS_7SimplexILt3ELt1ELt3EEEdLi
0EEEEENS4_INS_21OperatorInterpolationINS_13FunctionSpaceIS8_NS_5basesIJNS_8LagrangeILt3ENS_6ScalarENS_13DiscontinuousENS_18PointSetEquiSpacedELt0EEEEEENS3_9parameter5voi
d_ESK_SK_EESL_NS3_6tuples5tupleIN4mpl_6size_tILm0EEEN9__gnu_cxx17__normal_iteratorIPKNS3_17reference_wrapperIKNS_12GeoElement3DILt3ES7_dEEEESt6vectorISX_SaISX_EEEES13_St
10shared_ptrIS12_ENSM_9null_typeES16_S16_S16_S16_S16_EENS_26InterpolationNonConformingEEEEENS4_INSA_INSB_IS8_NSC_IJNSD_ILt3ENS_9VectorialESF_SG_Lt0EEEEEEdNS_11Periodicit
yIJNS_13NoPeriodicityEEEENS_7mortarsIJNS_8NoMortarEEEEEES1K_S17_S18_EEEE+0x4119)[0x87ea59]
./feelpp_toolbox_mixed-poisson-model_3DP3[0x78563f]
./feelpp_toolbox_mixed-poisson-model_3DP3(main+0xdb1)[0x76bd81]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f6c3642b3f1]
./feelpp_toolbox_mixed-poisson-model_3DP3(_start+0x2a)[0x76aefa] `

**Comment by lsala** [comment]
![errorscreen](https://user-images.githubusercontent.com/19267737/29665615-2731bb68-88d5-11e7-9d36-94363232363a.png)

**Comment by prudhomm** [comment]
The back trace tells you that there is a call to `free` on an invalid  pointer. To find  the line execute the code in gdb. Type `catch throw` in gdb 
 before running the code.

**Comment by prudhomm** [comment]
Of course you would need to be in Debug build type with cmake

**Comment by lsala** [comment]
yes, indeed I'm recompiling everything in debug mode to test it

**Comment by lsala** [comment]
![errorscreen](https://user-images.githubusercontent.com/19267737/29675516-a9685fe0-88f5-11e7-856c-6cbdea4ed16e.png)

**Comment by lsala** [comment]
The crash ( corrupted memory access ) is coming from these lines:
`auto l2err_u = normL2(_range=elements(M_mesh), _expr= u_exact - idv(M_up));
auto l2norm_uex = normL2( _range=elements(M_mesh), _expr= u_exact );`

**Comment by romainhild** [comment]
In fact there was two bugs:
- in parallel the export of the boundary condition crashed due to the access of `M_mup[i][0]` in a `Feel::cout` but the master proc didn't have necessary some dofs in the integral boundary. This is fixed by 1d2d597b6a119e843701a8b3f2c0fa4734aa4537
- and in sequential, at order greater than 3, a crash occurs when creating expressions for `gradp_exact` and `u_exact` at those lines:
https://github.com/feelpp/feelpp/blob/1d2d597b6a119e843701a8b3f2c0fa4734aa4537/toolboxes/feel/feelmodels/hdg/mixedpoisson.hpp#L1612-L1628
This is fixed by 298fe2c269ec993ebb907195eec8eed2c6e29562.

By the way @lsala, the indentation of the two last lines is wrong. You probably have a problem in your emacs, you should add those lines in your `.emacs` or `init.el` file:
```
(setq-default indent-tabs-mode nil)
```

**Comment by lsala** [comment]
Thank you @romainhild but I still don't understand the problems of indentation since now I have the proper configuration
